---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "My atreus keyboard build"
keywords:    "atreus keyboard"
description: "Some notes about my atreus keyboard build"
source_link: "https://github.com/hartzell/atreus-build"
favicon:     "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:      '#111111'
  darkgrey:   '#222222'
  white:      '#f8f8f8'
  whitesmoke: '#f5f5f5'
  blue:       '#49a7e9'
  green:      '#9bcf2f'
  purple:     '#c869bf'
  orange:     '#fab125'
  turquoise:  '#0fbfcf'

kramdown:
  auto_ids:  false
